name: library_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^5.0.3
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1
  dio: ^4.0.6
  http: ^0.13.5
  intl: ^0.17.0
  charts_flutter: ^0.12.0

  design_system_library_flutter:
    git:
      url: "https://github.com/DSantos69/library-flutter-front-system-design.git"
      path: ./
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

